name: build

permissions: read-all

on:
  push:
  pull_request:
  schedule:
  - cron: "34 8 * * 3"  # Run at a random time weekly

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup conda and dependencies
      run: |
        tools/setup_ci.sh ~/deps ${{ matrix.python-version }}
    - name: Test
      run: |
        export PATH=~/deps/bin:$PATH
        eval "$(conda shell.bash hook)"
        conda activate python${{ matrix.python-version }}
        mkdir build && cd build
        cmake .. -DIMP_DIR=${CONDA_PREFIX}/lib/cmake/IMP
        make
        ./setup_environment.sh pytest --cov=.. --cov-branch --cov-report=xml -v ../test/test*.py
        flake8 ../pyext/src/
    - uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
